"use client";

import { useEffect, useState } from "react";
import { getActiveAlerts, resolveAlert } from "@/lib/api";
import { AlertItem } from "@/types/prediction";


export default function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  async function loadAlerts() {
    setLoading(true);
    setErrorMessage("");

    try {
      const items = await getActiveAlerts();
      setAlerts(items);
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to load alerts."
      );
    } finally {
      setLoading(false);
    }
  }

  async function handleResolveAlert(alertId: number) {
  setErrorMessage("");

  try {
    await resolveAlert(alertId);
    await loadAlerts();
  } catch (error) {
    setErrorMessage(
      error instanceof Error ? error.message : "Failed to resolve alert."
    );
  }
  }

  useEffect(() => {
    loadAlerts();
  }, []);

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-8 text-slate-900">
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <p className="text-sm font-semibold text-red-700">
              Sepsis Alert Monitoring
            </p>
            <h1 className="mt-2 text-3xl font-bold">Active Alerts</h1>
            <p className="mt-2 text-slate-600">
              Review active high-risk sepsis alerts generated by the CDSS.
            </p>
          </div>

          <button
            onClick={loadAlerts}
            disabled={loading}
            className="rounded-xl bg-red-600 px-4 py-3 font-semibold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:bg-slate-400"
          >
            {loading ? "Refreshing..." : "Refresh Alerts"}
          </button>
        </div>

        {errorMessage && (
          <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            {errorMessage}
          </div>
        )}

        {loading && (
          <div className="rounded-2xl bg-white p-6 shadow-sm">
            <p className="text-slate-600">Loading alerts...</p>
          </div>
        )}

        {!loading && alerts.length === 0 && (
          <div className="rounded-2xl bg-white p-6 shadow-sm">
            <h2 className="text-xl font-semibold">No active alerts</h2>
            <p className="mt-2 text-slate-600">
              There are currently no active high-risk sepsis alerts.
            </p>
          </div>
        )}

        {!loading && alerts.length > 0 && (
          <div className="grid gap-4">
            {alerts.map((alert) => (
              <div
                key={alert.id}
                className="rounded-2xl border border-red-100 bg-white p-6 shadow-sm"
              >
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm font-semibold text-red-700">
                      Alert #{alert.id}
                    </p>
                    <h2 className="mt-1 text-xl font-bold">
                      Patient Code: {alert.patient_code}
                    </h2>
                    <p className="mt-1 text-sm text-slate-500">
                    Database patient ID: {alert.patient_id}
                    </p>
                    <p className="mt-2 text-slate-700">{alert.message}</p>
                  </div>

                  <span className="rounded-full bg-red-100 px-3 py-1 text-sm font-semibold text-red-700">
                    {alert.priority}
                  </span>
                </div>

                <div className="mt-4 grid gap-3 text-sm text-slate-600 md:grid-cols-3">
                  <p>
                    Prediction ID:{" "}
                    <span className="font-semibold text-slate-900">
                      {alert.prediction_id}
                    </span>
                  </p>
                  <p>
                    Status:{" "}
                    <span className="font-semibold text-slate-900">
                      {alert.is_active ? "Active" : "Resolved"}
                    </span>
                  </p>
                  <p>
                    Created:{" "}
                    <span className="font-semibold text-slate-900">
                      {new Date(alert.created_at).toLocaleString()}
                    </span>
                  </p>
                </div>
                <button
                onClick={() => handleResolveAlert(alert.id)}
                className="mt-4 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-red-700 ring-1 ring-red-200 hover:bg-red-100">
                Mark as Resolved
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </main>
  );
}